Traceback (most recent call last):
  File "C:/Users/suryakislaya/Documents/GitHub/practice-experiments/debugging Experiments.py", line 29, in <module>
    raise Exception ('This is the error message.')
Exception: This is the error message.
